spring:
    application:
        name: gpsminiapp
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
        serialization:
          INDENT_OUTPUT: true
    redis:
        database: 2
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}
        pool:
        max-active: 20
        password: ${REDIS_PASSWORD:123456}
    cache:
        type: redis
        cache-names: userdetail,cache1
        redis:
          cache-null-values: true
          key-prefix: userdetail_
          time-to-live: 0ms
          use-key-prefix: true
    jpa:
        hibernate:
          ddl-auto: none
        show-sql: true
        properties:
          hibernate:
            dialect: com.jldata.pgsminiapp.core.jdbc.MySQL5DialectUTF8
        database: mysql
    datasource:
          name: test
          url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/test?useUnicode=true&characterEncoding=UTF8
          username: db_test
          password: db_test
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
server:
    port: 9778 #启动端口

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800

logging:
  level:
    root: info
    org.springframework.web: error
    org.hibernate: error


